
# This file was generated by 'versioneer.py' (0.7) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.1'
version_full = '71d7ef53449f8f74047907787fc6d475c04e4435'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

